### ISSUE TITLE
Interaction is buggy

### ISSUE THREAD

**Issue by wooorm** [velomovies/fe3-assessment-2#1]
Something’s up with the select, I can sometimes select a few different years, and it updates, but then when I try another year it doesn’t. I’m not entirely sure what’s happening, but I saw it in Safari and Chrome.

**Comment by velomovies** [comment]
Hmm thats weird. I think it is because of the styling I added to the select. Should I remove that styling, so you can try if the bug is gone?

**Comment by wooorm** [comment]
You don‘t notice the same bug?

**Comment by wooorm** [comment]
To reproduce: select the first, then the second, etc, and after a while they don’t "work" anymore for me.

**Comment by velomovies** [comment]
Aah okay. Hmm I don't notice the same bug. I changed the years 40 times or so and it keeps updating... (using chrome)

**Comment by velomovies** [comment]
and also in firefox

**Comment by velomovies** [comment]
The only weird thing is that you can't click on the select dropdown arrow, but only on the text: "year [date]" 
Maybe that is the problem

**Comment by wooorm** [comment]
You’re using the `'click'` event, but you should probably use [`'change'`](https://github.com/cmda-fe3/course-17-18/blob/75667df91ace0b40e787e48f1aa805bb0a89f2b1/site/class-4/axis/index.js#L66)?

**Comment by velomovies** [comment]
Yeah I think so. I didn't know its existance before you explained it in the last class. Thats why I didn't use it. Do you want me to change that or leave it how it how it is?

**Comment by wooorm** [comment]
Yup! why not?!

**Comment by velomovies** [comment]
Updated index.js with:
```javascript 
dropSelect.on("change", selectUpdate)
```

**Comment by wooorm** [comment]
It works!
